# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-30 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(max_length=200, verbose_name='\u56de\u7b54'),
        ),
    ]
