# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-30 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20180830_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(max_length=1000, verbose_name='\u56de\u7b54'),
        ),
    ]
