# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proname', models.CharField(max_length=100, verbose_name='\u7cfb\u7edf\u542f\u52a8\u7a0b\u5e8f\u540d')),
                ('operate', models.CharField(max_length=100, verbose_name='\u663e\u793a\u5728\u64cd\u4f5c\u754c\u9762\u7684\u540d\u5b57-\u4e2d\u6587')),
            ],
            options={
                'db_table': 'programinfo',
                'verbose_name': '\u542f\u52a8\u7a0b\u5e8f\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u542f\u52a8\u7a0b\u5e8f\u4fe1\u606f\u8868',
            },
        ),
    ]
