# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_programinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programinfo',
            name='operate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u663e\u793a\u5728\u64cd\u4f5c\u754c\u9762\u7684\u540d\u5b57-\u4e2d\u6587'),
        ),
    ]
